### ISSUE TITLE
what about caching static files in entry proxy?

### ISSUE THREAD

**Issue by starius** [DonnchaC/oniongateway#1]

**Comment by david415** [comment]
what? we cannot cache content since we are transparently proxying a TLS stream.

what do you mean by gateway? donncha's design specifies the hidden service servers, entry proxies and authoritative DNS servers. there's isn't a component called the gateway.

**Comment by starius** [comment]
> what? we cannot cache content since we are transparently proxying a TLS stream.

Can you use [Keyless SSL](https://www.cloudflare.com/keyless-ssl/) approach invented by CloudFlare?

> what do you mean by gateway?

s/gateway/entry proxy/

**Comment by DonnchaC** [comment]
@starius Thanks for your interest. No with this design we want to remove all abilities for the proxy servers to be able to view or modify the traffic content. The proxy servers will forward the raw TLS streams to the hidden service endpoints.

CloudFlare's **Keyless SSL** is not actually key less. CloudFlare doesn't get access the the CA signed private key but they do get copies of all the session encryption keys for the client connections. They are acting as a full man-in-the-middle who can view and modify all of the traffic.
